### ISSUE TITLE
添加 luci-app-diskman

### ISSUE THREAD

**Issue by tossp** [281677160/openwrt-package#13]
https://github.com/lisaac/luci-app-diskman

**Comment by 281677160** [comment]
&nbsp;luci-app-diskman 这插件，源码不是自带吗？




---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月18日(周四) 凌晨1:22
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [281677160/openwrt-package] 添加 luci-app-diskman (#13)




 
https://github.com/lisaac/luci-app-diskman
