### ISSUE TITLE
可以整个京东签到插件么

### ISSUE THREAD

**Issue by lee29** [281677160/openwrt-package#19]
RT

**Comment by 281677160** [comment]
什么源码的？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/openwrt-package"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月2日(星期五) 晚上11:40
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[281677160/openwrt-package] 可以整个京东签到插件么 (#19)





 
RT

**Comment by 281677160** [comment]
我查了下，我仓库的全部源码都带京东签到插件的啊

**Comment by lee29** [comment]
lienol的。make menuconfig没看到有哦

**Comment by 281677160** [comment]
![QQ截图20210703010930](https://user-images.githubusercontent.com/66651997/124308142-67a1c180-db9b-11eb-9fc5-77b4d0085ff8.png)

这个不是京东签到吗？OP好像就一个人写这个东西吧

**Comment by 281677160** [comment]
我特意确认过插件包是有的，刚才都手动删除又拉取，来来去去的确认真有啊

**Comment by 281677160** [comment]
看了你仓库，把你扩展文件拉取插件的代码全部删掉，我插件包全自带的，重复拉取干嘛

**Comment by lee29** [comment]
![image](https://user-images.githubusercontent.com/9483929/124324500-a3498500-dbb5-11eb-9ddd-979ffdf60f03.png)
![image](https://user-images.githubusercontent.com/9483929/124324941-616d0e80-dbb6-11eb-8993-e7e72f583936.png)

京东签到的已经注释掉了，还是没有出现luci-app-jd-dailybonus。是不是跟下面还留有我的argon主题配置有关[这个是自己改了主题所以需要存在的]，还是说\build\Lienol_source\files\etc\config里我存了jd-dailybonus配置文件导致的？

**Comment by lee29** [comment]
还有个问题就是[*] UnblockNeteaseMusic NodeJS Version  选上了编译出来固件没有。。。

**Comment by 281677160** [comment]
你这个问题很诡异啊，我也没搞明白，源码里面肯定是带京东签到的，还有就是你说的[*] UnblockNeteaseMusic NodeJS Version问题，这个是源码本身自带插件，我也没去了解过，等我有时间了编译测试才知道，如果你自己拉我仓库有重覆的插件，应该删除对应位置的插件再拉取，你的删除没删除对应的位置

find . -name 'luci-app-argon-config' -o -name 'luci-theme-argon'  | xargs -i rm -rf {}
git clone -b 18.06 https://github.com/lee29/luci-theme-argon package/luci-theme-argon
git clone https://github.com/lee29/luci-app-argon-config package/luci-app-argon-config

你要拉取就这样拉取，第一行代码是无差别的找这2个文件夹，不管在什么位置的，有就删除，然后就是拉取你要的

**Comment by 281677160** [comment]
我拉取你的仓库测试了，你的机型或者说是CPU压根就不支持京东签到，还有luci-app-unblockmusic这个插件，你没有选择luci-app-unblockmusic，只有子项[*] UnblockNeteaseMusic NodeJS Version可定是不能编译出来的

**Comment by lee29** [comment]
> 我拉取你的仓库测试了，你的机型或者说是CPU压根就不支持京东签到，还有luci-app-unblockmusic这个插件，你没有选择luci-app-unblockmusic，只有子项[*] UnblockNeteaseMusic NodeJS Version可定是不能编译出来的

jd肯定是支持的，因为前两个月我用你之前的旧版本的github action然后git clone其他源是能编译出来而且使用的。是不是现在的jd签到不支持我的cpu了？

**Comment by 281677160** [comment]
> > 我拉取你的仓库测试了，你的机型或者说是CPU压根就不支持京东签到，还有luci-app-unblockmusic这个插件，你没有选择luci-app-unblockmusic，只有子项[*] UnblockNeteaseMusic NodeJS Version可定是不能编译出来的
> 
> jd肯定是支持的，因为前两个月我用你之前的旧版本的github action然后git clone其他源是能编译出来而且使用的。是不是现在的jd签到不支持我的cpu了？

你自己看啊，就你的机型是不显示京东签到跟luci-app-unblockmusic的，你就在配置固件那里转换一下机型，比如转换成X86的，再去看插件，立马就显示了

**Comment by lee29** [comment]
> > > 我拉取你的仓库测试了，你的机型或者说是CPU压根就不支持京东签到，还有luci-app-unblockmusic这个插件，你没有选择luci-app-unblockmusic，只有子项[*] UnblockNeteaseMusic NodeJS Version可定是不能编译出来的
> > 
> > 
> > jd肯定是支持的，因为前两个月我用你之前的旧版本的github action然后git clone其他源是能编译出来而且使用的。是不是现在的jd签到不支持我的cpu了？
> 
> 你自己看啊，就你的机型是不显示京东签到跟luci-app-unblockmusic的，你就在配置固件那里转换一下机型，比如转换成X86的，再去看插件，立马就显示了
lede的源码这两个都有的，但为啥lienol的都没有了。是内核问题吗还是？

**Comment by lee29** [comment]
> > > 我拉取你的仓库测试了，你的机型或者说是CPU压根就不支持京东签到，还有luci-app-unblockmusic这个插件，你没有选择luci-app-unblockmusic，只有子项[*] UnblockNeteaseMusic NodeJS Version可定是不能编译出来的
> > 
> > 
> > jd肯定是支持的，因为前两个月我用你之前的旧版本的github action然后git clone其他源是能编译出来而且使用的。是不是现在的jd签到不支持我的cpu了？
> 
> 你自己看啊，就你的机型是不显示京东签到跟luci-app-unblockmusic的，你就在配置固件那里转换一下机型，比如转换成X86的，再去看插件，立马就显示了

是不是引用的common,sh里面的地址问题。lienol源码里面package/lean下就有luci-app-unblockmusic，是不是不能全部把包都放在diy目录而是要分开diy目录和lean目录`cp -Rf "${Home}"/build/common/LIENOL/diy/* "${Home}"`

**Comment by 281677160** [comment]
luci-app-unblockmusic这个是源码自带的插件，没有你机型选择你可以去问源码的作者，看看他有没有心情给你弄，至于京东签到的问题，你可以去插件源码作者那里问问的，或者你也可以随带的两个插件一起跟固件源码作者提提，看看他弄不弄了

**Comment by 281677160** [comment]
源码跟插件有兼容性问题，你可以去源码作者那里提问一下的，态度好点，说明白你用源码的分支，说清楚你的问题，这样源码作者不解决，其他人看到如果懂的话，也可以给你解决方法的，不要怕啊，我经常去几个源码作者那里提问

**Comment by 281677160** [comment]
这些两插件在同源码其他机型上都有选择，就你的机型没选择的，不存在说拉插件的时候拉错了，或者放错位置的问题
