### ISSUE TITLE
辣鸡大水狼

### ISSUE THREAD

**Issue by AK201314** [281677160/openwrt-package#23]
飞机群什么玩意儿人都有，举报到底……

**Comment by shidahuilang** [comment]
麻痹的，你是傻子吗？进群来就JJYY的问人怎么完善你的脚本，群主的脚本不能用？
你要完善你脚本，你问人家，人家回答你是人家情愿，人家不回答你就是得罪你了？你是谁啊？
搞了几天没搞好你的脚本，用群主的脚本说加插件错误，群主问你加什么插件，发出来看看，你鸟都不鸟他，简直就是牛逼的不行
等群主没空的时候就发出来说啥啥的，人家专门等着伺候你这个大爷的？
一直瞎逼逼的问，我也就安安心心用群主的脚本而已，我就是没技术不行？我没技术得罪你？三更半夜的一直在@这个@那个，哥们深夜两点了，老子都把这个插件搞定了，你个傻逼还在一直BB，就你用个K2P 16M内存的玩尼玛的软路由，穷逼一个！！
就你这样的傻逼，地球有多远你就滚多远就对了
