### ISSUE TITLE
请问这个怎么使用在openwrt的网页后台种？

### ISSUE THREAD

**Issue by luchen7** [281677160/openwrt-package#26]
请问这个怎么使用在openwrt的网页后台种？

**Comment by 281677160** [comment]
这个是编译固件用的

**Comment by luchen7** [comment]
请问可以加一下我的微信吗  我想请教您一些问题

**Comment by luchen7** [comment]
luchen7

**Comment by luchen7** [comment]
这个就是最新版本的PASSWALL吗

**Comment by 281677160** [comment]
呃，要PASSWALL你自己去作者那里拉取就好了呗

**Comment by 281677160** [comment]
有什么问题直接问，能回答就回答






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/openwrt-package"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月29日(星期二) 晚上11:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [281677160/openwrt-package] 请问这个怎么使用在openwrt的网页后台种？ (Issue #26)





 
你可以加我一下吗  请教几个问题

**Comment by luchen7** [comment]
如果我想添加pass  是不是编译的时候修改  diy-part1.sh ？    请问具体怎么添加

**Comment by luchen7** [comment]
我现在急需一版本固件   就只需要 passwall   smartdns   和 argon主题   弄了几天实在弄不好

**Comment by 281677160** [comment]
自己不会编译就去恩山下载吧，多的是




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/openwrt-package"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月29日(星期二) 晚上11:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [281677160/openwrt-package] 请问这个怎么使用在openwrt的网页后台种？ (Issue #26)





 
我现在急需一版本固件   就只需要 passwall   smartdns   和 argon主题   弄了几天实在弄不好

**Comment by luchen7** [comment]
请问pass最新版本号是多少，我可以找你定制一个固件吗？
