### ISSUE TITLE
希望可以加个钉钉推送

### ISSUE THREAD

**Issue by qhq** [281677160/openwrt-package#9]
希望加个钉钉推送
库地址
https://github.com/zzsj0928/luci-app-serverchand.git

**Comment by 281677160** [comment]
加了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/openwrt-package"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月30日(星期六) 凌晨0:48
收件人:&nbsp;"281677160/openwrt-package"<openwrt-package@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[281677160/openwrt-package] 希望可以加个钉钉推送 (#9)





 
希望加个钉钉推送
 库地址
 https://github.com/zzsj0928/luci-app-serverchand.git
